### ISSUE TITLE
[workshop studio]Text needs editor who knows English well

### ISSUE THREAD

**Issue by EvanWMorton** [aws-samples/data-engineering-for-aws-immersion-day#23]
Sorry this is so broad.  The text of the workshop needs to be edited by someone who speaks English well, which probably means someone who speaks it as their first language.  The mistakes in grammar, spelling, and punctuation make the workshop harder to read.  I'm not going to list those mistakes, as it would take a long time, but the latter part of the workshop has more errors.

**Comment by melodyyangaws** [comment]
Thanks for the request. This repo is used for tracking CloudFormation template changes. Our official lab instructions can be found here: https://catalog.us-east-1.prod.workshops.aws/v2/workshops/976050cc-0606-4b23-b49f-ca7b8ac4b153/en-US/ . The Redshift lab instruction are not maintained because they have never been part of the Data Engineering Immersion day.

**Comment by EvanWMorton** [comment]
Sorry, part of your comment doesn't make sense to me.  You mention that the "Redshift lab instruction" are not maintained, but the issue I raised has nothing to do with a Redshift lab.

More importantly, the lab instructions I was using (the same one you pointed to in your reply) have text at the very end of the "Wrapping Up" section saying that if we have issues we should report them by creating an issue in this repo.  So I was following the instructions for giving feedback.  If those instructions aren't right, can you fix them?  If not, can you pass this on to someone who can?  Thanks.

**Comment by melodyyangaws** [comment]
I see. The comment in the "Wrapping Up" section is new, thanks for pointing it out.  We will update the text to provide a clear guidance in terms of how to create an issue for the workshop website, not for this repo.

Coming back to your request, do you mind to list some major problems that impact on user experience? which exact part of the workshop or labs has more errors? Hopefully you can provide more details that help us identify the lab owners and assign the issues accordingly.

**Comment by EvanWMorton** [comment]
You asked me to "list some major problems that impact on user experience".
I cannot, because there are no major problems, just many small ones.  Here
are a few.

A simple example: at
https://catalog.us-east-1.prod.workshops.aws/v2/workshops/976050cc-0606-4b23-b49f-ca7b8ac4b153/en-US/400/401/430-main-lab
it says "Before start".  The correct phrase is "Before starting".  But you
could also just remove that whole phrase and call that step 1.

At
https://catalog.us-east-1.prod.workshops.aws/v2/workshops/976050cc-0606-4b23-b49f-ca7b8ac4b153/en-US/100-introduction/20-aws-account
it says "In case" when it means "If".  The phrase "in case" is widely
misunderstood by ESL students to mean "if", but it does not.

At
https://catalog.us-east-1.prod.workshops.aws/v2/workshops/976050cc-0606-4b23-b49f-ca7b8ac4b153/en-US/400/401/430-main-lab
it uses "will look like below:" in two places.  The word "below" doesn't
belong, both because it's not literally below and because the colon takes
care of that.

This isn't really an example of an English issue, but at
https://catalog.us-east-1.prod.workshops.aws/v2/workshops/976050cc-0606-4b23-b49f-ca7b8ac4b153/en-US/300/320-main-lab
search for "dropdown c".  You'll see a place where steps are called
a,b,c,d, but with steps b, c, d run together in one paragraph.  In other
words, there is a missing line feed for each of c and d.  This makes it
harder to read.  The problem occurs elsewhere in the lab.

These should be sufficient to give you the general idea.  You simply need
to have a native English speaker read through.  They'll find many issues to
fix.

You wrote that you expect to "identify the lab owners and assign the issues
accordingly".  That might not work.  If the same people who wrote the pages
read them, they won't necessarily see the mistakes.  It would be better to
have one native English speaker, preferably a techwriter, do it all.

Thanks.

**Comment by code2648** [comment]
We started tech-editor review and will update this issue once completed.

**Comment by EvanWMorton** [comment]
Great!  Thanks.

**Comment by code2648** [comment]
tech review completed.
