### ISSUE TITLE
dms_sample.sporting_event_ticket table ticketholder_id NULL

### ISSUE THREAD

**Issue by gpoul** [aws-samples/data-engineering-for-aws-immersion-day#3]
When I recreate the instructor environment, based on the Athena/QuickSight lab, I would expect the ticketholder_id fields in sporting_event_ticket table to be non-null.

In my recreated RDS PostgreSQL DB the fields are all NULL and the following query does not return a single row:

```
SELECT * FROM dms_sample.sporting_event_ticket
WHERE ticketholder_id != NULL;
```

**Comment by melodyyangaws** [comment]
The `ticketholder_id` column will be null at the beginning of the database creation. Please wait for 20 minutes to complete the database setup, once the CloudFormation stack "dmslab-instructor" is in the status of "CREATE_COMPLETE", then proceed with the DMS lab.
