### ISSUE TITLE
Get spammed with ClkStrEv2: Unable to delete SNS Subscriptions 

### ISSUE THREAD

**Issue by ilok-ops** [aws-samples/data-engineering-for-aws-immersion-day#37]
Hi, 
I have attended AWS Workshop, despite cleanup exercise (https://catalog.us-east-1.prod.workshops.aws/event/dashboard/en-US/workshop/2000)  account still appears in inconsistent state.

1. SNS Topic Deleted, while subscriptions impossible to delete. Unable to unsubscribe either.
2. While topic deleted , it is still referenced by subscriptions and metrics
3. Even though Lambda function deleted, I'm still receiving emails from SNS:
Subj:  ClkStrEv2
Body: Anomaly detected with a click through rate of undefined% and an anomaly score of undefined

More info:
Account ID: 2345-3900-6039
Federated user: WSParticipantRole/Participant

**Comment by melodyyangaws** [comment]
In your previous subscription confirmation email,  click confirmation button, in the 2nd pop up page, it has a link [click here to unsubscribe]() . please unsubscribe it. Thanks.
