### ISSUE TITLE
PostgreSQL : extended support

### ISSUE THREAD

**Issue by psantus** [aws-samples/data-engineering-for-aws-immersion-day#38]
First, thanks for this amazing workshop. 

I just wanted to remind you that PGSql 11 is now under extended support. Switching to newer version would keep the cost low for self-paced students ^^
https://github.com/aws-samples/data-engineering-for-aws-immersion-day/blob/master/PreLab/0.0-PreLab-DMSLab_instructor_CFN.yaml#L253

**Comment by melodyyangaws** [comment]
have upgraded to the latest version 16.4
