### ISSUE TITLE
ROLLBACK_IN_PROGRESS

### ISSUE THREAD

**Issue by mustafameruyert** [aws-samples/data-engineering-for-aws-immersion-day#5]
Hello I am following this guide https://aws-dataengineering-day.workshop.aws/en/400/420-pre-lab-2.html.Prelab setup 1 was done successfully but in Prelab setup 2 I have next [problems:]
![picture](https://user-images.githubusercontent.com/43790316/86095447-bffb3a80-bad3-11ea-869d-fa33c2fb5fa4.png)

**Comment by melodyyangaws** [comment]
@mustafameruyert what was the error when it was rolling back? can you try again?

**Comment by mustafameruyert** [comment]
> @mustafameruyert what was the error when it was rolling back? can you try again?

Hello I found my error.Changed password in json file and it works now
